steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
  id: Environmnet Setup
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      set -x
      gcloud services enable storage.googleapis.com --project ${PROJECT_ID} > /dev/null
      gcloud services enable bigquery.googleapis.com --project ${PROJECT_ID} > /dev/null

- id: 'Import Dataset into BigQuery'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
  entrypoint: 'bash'
  args: 
  - '-c'
  - | 
      echo "******************************************"
      echo "Pulling latest Dataset from URL"
      echo "******************************************"

      curl ${_BQ_DATASET_URL} --output ${_GCS_FILE_NAME}

      echo "******************************************"
      echo "Upload Dataset to GCS"
      echo "******************************************"

      if [ -n "$(gsutil ls gs://${_GCS_BUCKET_NAME}/)" ]; then
        gsutil cp ./${_GCS_FILE_NAME} gs://${_GCS_BUCKET_NAME}/
      else
        echo "BUCKET DOES NOT EXIST... CREATING..."
        gsutil mb -l ${_LOCATION} gs://${_GCS_BUCKET_NAME}
        
        echo "UPLOADING DATASET TO GCS..."
        gsutil cp ./${_GCS_FILE_NAME} gs://${_GCS_BUCKET_NAME}/
      fi
      
      echo "******************************************"
      echo "Load Dataset into BigQuery"
      echo "******************************************"

      if [ -n "$(bq ls --filter labels.name:${_BQ_DATASET_NAME} --project_id ${PROJECT_ID})" ]; then
        bq load \
          --location=${_LOCATION} \
          --source_format=${_BQ_DATASET_FORMAT} \
          --autodetect \
          --replace ${_BQ_DATASET_NAME}.${_BQ_TABLE_NAME} \
          gs://${_GCS_BUCKET_NAME}/${_GCS_FILE_NAME}
      else
        echo "BIGQUERY DATASET DOES NOT EXIST... CREATING..."
        bq mk \
          --location=${_LOCATION} \
          --dataset \
          --default_table_expiration 0 \
          --description "${_BQ_DATASET_DESCRIPTION}" \
          ${PROJECT_ID}:${_BQ_DATASET_NAME}

        bq update --set_label name:${_BQ_DATASET_NAME} ${PROJECT_ID}:${_BQ_DATASET_NAME}

        echo "LOADING DATASET INTO BIGQUERY..."
        bq load \
          --location=${_LOCATION} \
          --source_format=${_BQ_DATASET_FORMAT} \
          --autodetect \
          --replace ${_BQ_DATASET_NAME}.${_BQ_TABLE_NAME} \
        gs://${_GCS_BUCKET_NAME}/${_GCS_FILE_NAME}
      fi

      echo "******************************************"
      echo "Done"
      echo "******************************************"
substitutions:
    _LOCATION: northamerica-northeast1
    _BQ_DATASET_URL: https://covid.ourworldindata.org/data/owid-covid-data.csv
    _BQ_DATASET_NAME: superset_lab
    _BQ_DATASET_FORMAT: CSV
    _BQ_DATASET_DESCRIPTION: Complete Covid-19 CSV Dataset from OWID
    _BQ_TABLE_NAME: complete_worldwide_csv
    _GCS_BUCKET_NAME: owid_covid_data_2190731
    _GCS_FILE_NAME: owid_covid_data.csv
    
